### ISSUE TITLE
Marionette is not defined

### ISSUE THREAD

**Issue by aboyer1013** [JohnDMathis/Fleet#2]
Not sure if I'm missing anything, but according to your app.js file, if you load "modulehelper", it will always throw a "Marionette is not defined" error. Should "modulehelper.js" be wrapped in a define function call?

**Comment by JohnDMathis** [comment]
Thanks for your question.  The moduleHelper is required in the 'require' call on line 34, so the callback function will not be executed until after it's loaded.  I have not seen that 'Marionette is not defined' error.

**Comment by aboyer1013** [comment]
Thanks for the response. I was using AMD version of requireJS which was causing the error. I switched to the bundled non-AMD version instead and it worked.
